#!/usr/bin/env python3
# gen_nb_08.py -- generate notebooks/08-bert-2018.ipynb
import json, pathlib

cells = []

def code(src): return {'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': [], 'source': src}
def md(src): return {'cell_type': 'markdown', 'metadata': {}, 'source': src}

# -- Cell 0: Setup -------------------------------------------------------
cells.append(code(
    'import numpy as np\n'
    'import matplotlib\n'
    'matplotlib.rcParams["font.family"] = "DejaVu Sans"\n'
    'import matplotlib.pyplot as plt\n'
    'import warnings\n'
    'warnings.filterwarnings("ignore")\n'
    'np.random.seed(42)\n'
    'print("Setup complete")'
))

# -- Cell 1: Context-aware vs context-free word representations ----------
cells.append(md(
    '## Step 1: Why Context Matters\n\n'
    'word2vec / GloVe give the SAME vector to "bank" regardless of context.\n'
    'BERT gives DIFFERENT representations based on surrounding words.\n\n'
    'We simulate this with a tiny toy example.'
))

cells.append(code(
    '# Toy vocabulary (indices)\n'
    'vocab = {"[CLS]": 0, "[SEP]": 1, "[MASK]": 2, "[PAD]": 3,\n'
    '         "the": 4, "cat": 5, "sat": 6, "on": 7, "mat": 8,\n'
    '         "bank": 9, "river": 10, "money": 11, "loan": 12,\n'
    '         "near": 13, "deposited": 14, "fish": 15}\n'
    'VOCAB_SIZE = len(vocab)\n'
    'inv_vocab = {v: k for k, v in vocab.items()}\n'
    '\n'
    '# Context-free embedding: same vector for "bank" regardless of context\n'
    'np.random.seed(0)\n'
    'HIDDEN = 8\n'
    'context_free_emb = np.random.randn(VOCAB_SIZE, HIDDEN) * 0.3\n'
    '\n'
    '# Two sentences containing "bank"\n'
    'sent_river = ["the", "cat", "sat", "near", "river", "bank"]\n'
    'sent_money = ["she", "deposited", "money", "at", "the", "bank"]\n'
    '\n'
    'bank_idx = vocab["bank"]\n'
    'bank_vec = context_free_emb[bank_idx]\n'
    '\n'
    'print("Context-free: both \'bank\' have identical vector")\n'
    'print("bank vec (always same):", bank_vec.round(3))\n'
    'print()\n'
    'print("BERT will produce DIFFERENT vectors for \'bank\' in each sentence.")\n'
    'print("We will see this after building the BERT encoder below.")'
))

# -- Cell 2: Masked Language Model (MLM) --------------------------------
cells.append(md(
    '## Step 2: Masked Language Model (MLM)\n\n'
    'BERT randomly masks ~15% of tokens and trains to predict the originals.\n'
    'Of the selected tokens:\n'
    '- 80% are replaced with [MASK]\n'
    '- 10% are replaced with a random token\n'
    '- 10% are kept as-is\n\n'
    'This prevents the model from over-relying on the [MASK] signal.'
))

cells.append(code(
    'def mask_tokens(token_ids, vocab_size, mask_id=2,\n'
    '                mask_rate=0.15, mask_frac=0.8, random_frac=0.1,\n'
    '                rng=None):\n'
    '    """\n'
    '    Apply BERT-style masking to a list of token ids.\n'
    '    Returns:\n'
    '        masked_ids  -- input with some tokens replaced\n'
    '        labels      -- original ids at masked positions, -100 elsewhere\n'
    '        mask_flags  -- boolean array, True where a prediction target\n'
    '    """\n'
    '    if rng is None:\n'
    '        rng = np.random.default_rng(42)\n'
    '    ids = np.array(token_ids, dtype=np.int32)\n'
    '    labels = np.full_like(ids, -100)  # -100 = ignored in loss\n'
    '    n = len(ids)\n'
    '    # Step 1: select 15% of positions as targets\n'
    '    num_mask = max(1, int(n * mask_rate))\n'
    '    selected = rng.choice(n, size=num_mask, replace=False)\n'
    '    # Step 2: for each selected position, apply masking strategy\n'
    '    masked_ids = ids.copy()\n'
    '    for pos in selected:\n'
    '        labels[pos] = ids[pos]  # save original\n'
    '        r = rng.random()\n'
    '        if r < mask_frac:\n'
    '            masked_ids[pos] = mask_id        # 80%: [MASK]\n'
    '        elif r < mask_frac + random_frac:\n'
    '            masked_ids[pos] = rng.integers(0, vocab_size)  # 10%: random\n'
    '        # else: keep original (10%)\n'
    '    mask_flags = (labels != -100)\n'
    '    return masked_ids, labels, mask_flags\n'
    '\n'
    '# Example sentence: "the cat sat on the mat"\n'
    'sentence_ids = [vocab[w] for w in ["the", "cat", "sat", "on", "the", "mat"]]\n'
    'rng = np.random.default_rng(7)\n'
    'masked_ids, labels, mask_flags = mask_tokens(sentence_ids, VOCAB_SIZE, rng=rng)\n'
    '\n'
    'print("Original: ", [inv_vocab[i] for i in sentence_ids])\n'
    'print("Masked:   ", [inv_vocab[i] if i in inv_vocab else "?" for i in masked_ids])\n'
    'print("Labels:   ", [inv_vocab[l] if l != -100 else "_" for l in labels])\n'
    'print("Masked positions:", np.where(mask_flags)[0])'
))

# -- Cell 3: BERT Input Construction ------------------------------------
cells.append(md(
    '## Step 3: BERT Input Format\n\n'
    'Format: [CLS] sentence_A [SEP] sentence_B [SEP]\n\n'
    'Three types of IDs are required:\n'
    '- token_ids: the actual word token ids\n'
    '- segment_ids: 0 for sentence A, 1 for sentence B\n'
    '- position_ids: 0, 1, 2, ... up to max sequence length'
))

cells.append(code(
    'def make_bert_input(tokens_a, tokens_b, vocab):\n'
    '    """\n'
    '    Build BERT input from two token lists.\n'
    '    Returns token_ids, segment_ids, position_ids.\n'
    '    """\n'
    '    CLS, SEP = vocab["[CLS]"], vocab["[SEP]"]\n'
    '    # [CLS] + sent_A + [SEP] + sent_B + [SEP]\n'
    '    token_ids = [CLS] + tokens_a + [SEP] + tokens_b + [SEP]\n'
    '    segment_ids = [0] * (1 + len(tokens_a) + 1) + [1] * (len(tokens_b) + 1)\n'
    '    position_ids = list(range(len(token_ids)))\n'
    '    return (\n'
    '        np.array(token_ids, dtype=np.int32),\n'
    '        np.array(segment_ids, dtype=np.int32),\n'
    '        np.array(position_ids, dtype=np.int32)\n'
    '    )\n'
    '\n'
    'sent_a_ids = [vocab.get(w, 4) for w in ["the", "cat", "sat", "on", "the", "mat"]]\n'
    'sent_b_ids = [vocab.get(w, 4) for w in ["bank", "near", "river"]]\n'
    '\n'
    'token_ids, segment_ids, position_ids = make_bert_input(sent_a_ids, sent_b_ids, vocab)\n'
    '\n'
    'print("Sequence length:", len(token_ids))\n'
    'print("Expected:       ", 1 + len(sent_a_ids) + 1 + len(sent_b_ids) + 1)\n'
    'print("token_ids:   ", token_ids)\n'
    'print("segment_ids: ", segment_ids, "(0=sent_A, 1=sent_B)")\n'
    'print("position_ids:", position_ids)'
))

# -- Cell 4: BERT Embedding Layer ----------------------------------------
cells.append(md(
    '## Step 4: BERT Embedding Layer\n\n'
    'input_embed = token_embed + position_embed + segment_embed\n\n'
    'Unlike the original Transformer (fixed sinusoidal PE),\n'
    'BERT uses LEARNED position embeddings.'
))

cells.append(code(
    'class BERTEmbedding:\n'
    '    """\n'
    '    Three learnable embedding tables, summed together.\n'
    '    token_emb    : (vocab_size, hidden)\n'
    '    position_emb : (max_len, hidden)\n'
    '    segment_emb  : (2, hidden)  -- 0 = sent A, 1 = sent B\n'
    '    """\n'
    '    def __init__(self, vocab_size, hidden, max_len=512, seed=0):\n'
    '        rng = np.random.default_rng(seed)\n'
    '        scale = np.sqrt(1.0 / hidden)\n'
    '        self.token_emb    = rng.standard_normal((vocab_size, hidden)) * scale\n'
    '        self.position_emb = rng.standard_normal((max_len, hidden))    * scale\n'
    '        self.segment_emb  = rng.standard_normal((2, hidden))          * scale\n'
    '        self.hidden = hidden\n'
    '\n'
    '    def forward(self, token_ids, segment_ids, position_ids):\n'
    '        """\n'
    '        All inputs: 1-D integer arrays of length seq_len.\n'
    '        Returns: (seq_len, hidden)\n'
    '        """\n'
    '        tok = self.token_emb[token_ids]       # (seq_len, hidden)\n'
    '        pos = self.position_emb[position_ids] # (seq_len, hidden)\n'
    '        seg = self.segment_emb[segment_ids]   # (seq_len, hidden)\n'
    '        return tok + pos + seg\n'
    '\n'
    'emb_layer = BERTEmbedding(vocab_size=VOCAB_SIZE, hidden=HIDDEN, seed=1)\n'
    'X = emb_layer.forward(token_ids, segment_ids, position_ids)\n'
    '\n'
    'print("Embedding output shape:", X.shape)\n'
    'print("(seq_len=%d, hidden=%d)" % (len(token_ids), HIDDEN))\n'
    'print("Token emb shape:    ", emb_layer.token_emb.shape)\n'
    'print("Position emb shape: ", emb_layer.position_emb.shape)\n'
    'print("Segment emb shape:  ", emb_layer.segment_emb.shape)'
))

# -- Cell 5: BERT Encoder (Transformer Encoder Blocks) ------------------
cells.append(md(
    '## Step 5: BERT Encoder\n\n'
    'Stack L identical Transformer Encoder Blocks.\n'
    'Each block: Multi-Head Self-Attention -> Add & Norm -> FFN -> Add & Norm\n\n'
    'BERT-base: L=12, H=768, A=12. We use a toy version: L=2, H=8, A=2.'
))

cells.append(code(
    '# Reuse helpers from the Transformer node\n'
    'def softmax(x, axis=-1):\n'
    '    x = x - x.max(axis=axis, keepdims=True)\n'
    '    e = np.exp(x)\n'
    '    return e / e.sum(axis=axis, keepdims=True)\n'
    '\n'
    'def layer_norm(x, eps=1e-6):\n'
    '    mean = x.mean(axis=-1, keepdims=True)\n'
    '    std  = x.std(axis=-1,  keepdims=True)\n'
    '    return (x - mean) / (std + eps)\n'
    '\n'
    'def attention(Q, K, V):\n'
    '    d_k = Q.shape[-1]\n'
    '    scores = Q @ K.T / np.sqrt(d_k)\n'
    '    w = softmax(scores)\n'
    '    return w @ V, w\n'
    '\n'
    'class MHA:\n'
    '    def __init__(self, d_model, num_heads, seed=0):\n'
    '        assert d_model % num_heads == 0\n'
    '        rng = np.random.default_rng(seed)\n'
    '        self.h = num_heads\n'
    '        dk = d_model // num_heads\n'
    '        s = 0.1\n'
    '        self.WQ = [rng.standard_normal((d_model, dk)) * s for _ in range(num_heads)]\n'
    '        self.WK = [rng.standard_normal((d_model, dk)) * s for _ in range(num_heads)]\n'
    '        self.WV = [rng.standard_normal((d_model, dk)) * s for _ in range(num_heads)]\n'
    '        self.WO = rng.standard_normal((d_model, d_model)) * s\n'
    '    def forward(self, X):\n'
    '        heads = []\n'
    '        for i in range(self.h):\n'
    '            out, _ = attention(X @ self.WQ[i], X @ self.WK[i], X @ self.WV[i])\n'
    '            heads.append(out)\n'
    '        return np.concatenate(heads, axis=-1) @ self.WO\n'
    '\n'
    'class FFN:\n'
    '    def __init__(self, d_model, d_ff, seed=0):\n'
    '        rng = np.random.default_rng(seed)\n'
    '        self.W1 = rng.standard_normal((d_model, d_ff)) * 0.1\n'
    '        self.b1 = np.zeros(d_ff)\n'
    '        self.W2 = rng.standard_normal((d_ff, d_model)) * 0.1\n'
    '        self.b2 = np.zeros(d_model)\n'
    '    def forward(self, x):\n'
    '        return np.maximum(0, x @ self.W1 + self.b1) @ self.W2 + self.b2\n'
    '\n'
    'class EncoderBlock:\n'
    '    def __init__(self, d_model, num_heads, d_ff, seed=0):\n'
    '        self.mha = MHA(d_model, num_heads, seed=seed)\n'
    '        self.ffn = FFN(d_model, d_ff, seed=seed + 1)\n'
    '    def forward(self, X):\n'
    '        X = layer_norm(X + self.mha.forward(X))\n'
    '        X = layer_norm(X + self.ffn.forward(X))\n'
    '        return X\n'
    '\n'
    'class BERTEncoder:\n'
    '    def __init__(self, d_model, num_heads, d_ff, num_layers, seed=0):\n'
    '        self.layers = [EncoderBlock(d_model, num_heads, d_ff, seed=seed + i)\n'
    '                       for i in range(num_layers)]\n'
    '    def forward(self, X):\n'
    '        for layer in self.layers:\n'
    '            X = layer.forward(X)\n'
    '        return X\n'
    '\n'
    '# Tiny BERT: L=2 layers, H=8, A=2 heads\n'
    'bert_encoder = BERTEncoder(d_model=HIDDEN, num_heads=2, d_ff=16, num_layers=2, seed=99)\n'
    'H_all = bert_encoder.forward(X)  # (seq_len, hidden)\n'
    '\n'
    'print("Encoder input  shape:", X.shape)\n'
    'print("Encoder output shape:", H_all.shape)\n'
    'print("Output == Input shape:", H_all.shape == X.shape)'
))

# -- Cell 6: Classification Head (Fine-tuning) ---------------------------
cells.append(md(
    '## Step 6: Classification Head (Fine-tuning)\n\n'
    'The [CLS] token (position 0) aggregates the whole-sequence meaning.\n'
    'We add a single linear layer on top for classification tasks.\n\n'
    'Example: binary sentiment (positive / negative)'
))

cells.append(code(
    'class ClassificationHead:\n'
    '    def __init__(self, hidden, num_classes, seed=0):\n'
    '        rng = np.random.default_rng(seed)\n'
    '        self.W = rng.standard_normal((hidden, num_classes)) * 0.1\n'
    '        self.b = np.zeros(num_classes)\n'
    '    def forward(self, cls_vec):\n'
    '        """cls_vec: (hidden,) -> logits: (num_classes,)"""\n'
    '        return cls_vec @ self.W + self.b\n'
    '\n'
    '# Extract [CLS] vector (position 0)\n'
    'cls_vector = H_all[0]  # shape: (hidden,)\n'
    '\n'
    'head = ClassificationHead(hidden=HIDDEN, num_classes=2, seed=0)\n'
    'logits = head.forward(cls_vector)  # (2,)\n'
    'probs  = softmax(logits)\n'
    '\n'
    'print("[CLS] vector shape:", cls_vector.shape)\n'
    'print("Logits:", logits.round(4))\n'
    'print("Probs (positive / negative):", probs.round(4))\n'
    'print("Predicted class:", np.argmax(probs), "(0=neg, 1=pos)")\n'
    'print()\n'
    'print("This is fine-tuning in a nutshell:")\n'
    'print("  Pretrained BERT + 1 linear layer -> any classification task")'
))

# -- Cell 7: Pre-training Loss (MLM + NSP) -------------------------------
cells.append(md(
    '## Step 7: Pre-training Loss\n\n'
    'BERT is pre-trained with two losses:\n'
    '  L_total = L_MLM + L_NSP\n\n'
    'L_MLM: cross-entropy over masked positions\n'
    'L_NSP: binary cross-entropy for next-sentence prediction'
))

cells.append(code(
    'def cross_entropy_loss(logits, target_id):\n'
    '    """Cross-entropy for a single target class."""\n'
    '    log_probs = logits - np.log(np.sum(np.exp(logits - logits.max())) + 1e-9) - logits.max()\n'
    '    return -log_probs[target_id]\n'
    '\n'
    'def mlm_loss(H_all, labels, emb_layer, mask_flags):\n'
    '    """\n'
    '    H_all:      (seq_len, hidden) -- encoder output\n'
    '    labels:     (seq_len,) -- original ids at masked pos, -100 elsewhere\n'
    '    emb_layer:  BERTEmbedding (we reuse token_emb as the prediction weight)\n'
    '    mask_flags: boolean array, True at masked positions\n'
    '    """\n'
    '    # Project hidden states to vocab size\n'
    '    # W_vocab: (vocab_size, hidden) -- we reuse token embedding weights\n'
    '    W_vocab = emb_layer.token_emb  # (vocab_size, hidden)\n'
    '    total_loss = 0.0\n'
    '    count = 0\n'
    '    for i in np.where(mask_flags)[0]:\n'
    '        logits = H_all[i] @ W_vocab.T  # (vocab_size,)\n'
    '        total_loss += cross_entropy_loss(logits, labels[i])\n'
    '        count += 1\n'
    '    return total_loss / max(count, 1)\n'
    '\n'
    'def nsp_loss(cls_vector, head, is_next_label):\n'
    '    """\n'
    '    cls_vector:   (hidden,)\n'
    '    head:         ClassificationHead with 2 outputs (0=NotNext, 1=IsNext)\n'
    '    is_next_label: 0 or 1\n'
    '    """\n'
    '    logits = head.forward(cls_vector)  # (2,)\n'
    '    probs = softmax(logits)\n'
    '    return -np.log(probs[is_next_label] + 1e-9)\n'
    '\n'
    '# Need masked version of token_ids for a proper demo\n'
    'rng2 = np.random.default_rng(13)\n'
    'masked_ids2, labels2, mask_flags2 = mask_tokens(\n'
    '    token_ids.tolist(), VOCAB_SIZE, rng=rng2\n'
    ')\n'
    '# Recompute embeddings and encoder output for masked input\n'
    'X2 = emb_layer.forward(masked_ids2, segment_ids, position_ids)\n'
    'H2 = bert_encoder.forward(X2)\n'
    '\n'
    'l_mlm = mlm_loss(H2, labels2, emb_layer, mask_flags2)\n'
    'l_nsp = nsp_loss(H2[0], head, is_next_label=1)  # assume B follows A\n'
    'l_total = l_mlm + l_nsp\n'
    '\n'
    'print(f"MLM loss:   {l_mlm:.4f}")\n'
    'print(f"NSP loss:   {l_nsp:.4f}")\n'
    'print(f"Total loss: {l_total:.4f}")\n'
    'print()\n'
    'print("Both losses should be positive -- verified:", l_mlm > 0 and l_nsp > 0)'
))

nb = {
    'nbformat': 4, 'nbformat_minor': 5,
    'metadata': {
        'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
        'language_info': {'name': 'python', 'version': '3.10.0'}
    },
    'cells': cells
}

out = pathlib.Path(__file__).parent.parent / 'notebooks' / '08-bert-2018.ipynb'
out.write_text(json.dumps(nb, ensure_ascii=False, indent=1))
print(f'Written {out}')
