#!/usr/bin/env python3
"""gen_nb_14.py -- generate notebooks/14-gpt4-2023.ipynb"""

import json
from pathlib import Path

NB_PATH = Path(__file__).parent.parent / "notebooks" / "14-gpt4-2023.ipynb"
ASSETS = "../docs/assets"


def cell(cell_type, source, **kwargs):
    base = {
        "cell_type": cell_type,
        "metadata": {},
        "source": source if isinstance(source, list) else [source],
    }
    if cell_type == "code":
        base["outputs"] = []
        base["execution_count"] = None
    return {**base, **kwargs}


def md(*lines):
    return cell("markdown", "\n".join(lines))


def code(*lines):
    return cell("code", "\n".join(lines))


cells = [

    # ── Cell 0: Title ────────────────────────────────────────────────────────────
    md(
        "# 节点14：GPT-4 与涌现能力（2023）",
        "",
        "**核心问题**：为什么大模型能「突然会了」某些任务？",
        "",
        "本 notebook 用纯 NumPy 演示涌现现象的数学本质：",
        "1. 多步骤任务的组合概率如何产生 S 形跳变",
        "2. 模拟 BIG-Bench 风格的涌现曲线",
        "3. Chain-of-Thought（思维链）涌现演示",
        "4. GPT-4 vs GPT-3.5 的性能对比（基于报告数据）",
    ),

    # ── Cell 1: Imports ───────────────────────────────────────────────────────────
    code(
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "import matplotlib",
        "matplotlib.rcParams['font.family'] = ['DejaVu Sans', 'Arial Unicode MS', 'SimHei']",
        "matplotlib.rcParams['axes.unicode_minus'] = False",
        "",
        "np.random.seed(42)",
        "print('准备就绪！numpy:', np.__version__)",
    ),

    # ── Cell 2: Sigmoid函数讲解 ───────────────────────────────────────────────────
    md(
        "## Part 1：Sigmoid 函数——S 形曲线",
        "",
        "涌现能力在图上呈现出 S 形曲线。数学上叫 **Sigmoid 函数**：",
        "",
        "$$\\sigma(x) = \\frac{1}{1 + e^{-x}}$$",
        "",
        "它把任何实数 $x$ 映射到 $(0, 1)$ 之间，中间有一个陡峭的跳变区。",
    ),
    code(
        "def sigmoid(x, k=1.0, x0=0.0):",
        "    \"\"\"Sigmoid 函数：k 控制陡峭程度，x0 是拐点位置\"\"\"",
        "    return 1.0 / (1.0 + np.exp(-k * (x - x0)))",
        "",
        "x = np.linspace(-6, 6, 300)",
        "",
        "fig, axes = plt.subplots(1, 2, figsize=(12, 4))",
        "",
        "# 左图：不同 k 值",
        "for k, ls in [(0.5, '--'), (1.0, '-'), (3.0, ':')]:",
        "    axes[0].plot(x, sigmoid(x, k=k), ls, label=f'k={k}')",
        "axes[0].set_xlabel('x（模型规模，对数尺度）')",
        "axes[0].set_ylabel('任务准确率')",
        "axes[0].set_title('Sigmoid：S 形曲线')",
        "axes[0].legend()",
        "axes[0].axhline(0.5, color='gray', linestyle=':', alpha=0.5)",
        "axes[0].grid(True, alpha=0.3)",
        "",
        "# 右图：拐点右移",
        "for x0, color in [(0, 'blue'), (1, 'orange'), (2, 'green')]:",
        "    axes[1].plot(x, sigmoid(x, k=2.0, x0=x0), color=color, label=f'x0={x0}')",
        "axes[1].set_xlabel('x（模型规模）')",
        "axes[1].set_ylabel('任务准确率')",
        "axes[1].set_title('拐点右移 → 涌现阈值变大')",
        "axes[1].legend()",
        "axes[1].grid(True, alpha=0.3)",
        "",
        "plt.tight_layout()",
        f"plt.savefig(f'{ASSETS}/14-sigmoid.png', dpi=100, bbox_inches='tight')",
        "plt.close()",
        "print('Sigmoid 演示已保存')",
    ),

    # ── Cell 3: 多步骤任务涌现 ───────────────────────────────────────────────────
    md(
        "## Part 2：多步骤任务——为什么会「突然会了」？",
        "",
        "假设某任务需要 $n$ 个子步骤，每个步骤的成功率都随模型规模 $s$（对数）线性提升。",
        "整体成功率 = 每步成功率的乘积。",
        "",
        "即使每步是线性增长，乘积会产生「相变」式的跳变！",
    ),
    code(
        "def step_success_rate(log_scale, step_id, slope=0.2, base_offset=0.3):",
        "    \"\"\"",
        "    单步骤成功率：随模型规模对数线性增长，不同步骤有不同难度偏移。",
        "    clamp 到 [0.05, 0.98] 范围内（小模型还是有一定概率靠猜对）",
        "    \"\"\"",
        "    raw = slope * log_scale - base_offset - step_id * 0.1",
        "    return np.clip(raw, 0.05, 0.98)",
        "",
        "def task_success_rate(log_scale, n_steps):",
        "    \"\"\"n_steps 个子步骤的任务总成功率（各步骤独立）\"\"\"",
        "    product = np.ones_like(log_scale, dtype=float)",
        "    for i in range(n_steps):",
        "        product = product * step_success_rate(log_scale, i)",
        "    return product",
        "",
        "log_scales = np.linspace(0, 12, 300)  # 相当于模型参数从 1M 到 e^12 ≈ 160B",
        "",
        "fig, axes = plt.subplots(1, 2, figsize=(13, 5))",
        "",
        "# 左图：不同步骤数的涌现曲线",
        "colors = ['steelblue', 'orange', 'green', 'red', 'purple']",
        "for n, color in zip([1, 2, 3, 5, 8], colors):",
        "    rate = task_success_rate(log_scales, n)",
        "    axes[0].plot(log_scales, rate, color=color, label=f'{n} 步骤')",
        "",
        "axes[0].set_xlabel('log(模型参数量)')",
        "axes[0].set_ylabel('整体任务成功率')",
        "axes[0].set_title('步骤数越多，涌现越急剧')",
        "axes[0].legend()",
        "axes[0].axhline(0.5, color='gray', linestyle=':', alpha=0.5, label='50%线')",
        "axes[0].grid(True, alpha=0.3)",
        "",
        "# 右图：单步骤成功率 vs 5步骤任务对比",
        "single = step_success_rate(log_scales, 0)",
        "five = task_success_rate(log_scales, 5)",
        "axes[1].plot(log_scales, single, 'b-', label='单步骤（线性增长）')",
        "axes[1].plot(log_scales, five, 'r-', label='5步骤任务（乘积→相变）')",
        "axes[1].set_xlabel('log(模型参数量)')",
        "axes[1].set_ylabel('成功率')",
        "axes[1].set_title('单步线性增长 → 多步产生涌现')",
        "axes[1].legend()",
        "axes[1].grid(True, alpha=0.3)",
        "",
        "plt.tight_layout()",
        f"plt.savefig(f'{ASSETS}/14-emergence-steps.png', dpi=100, bbox_inches='tight')",
        "plt.close()",
        "print('多步骤涌现演示完成')",
    ),

    # ── Cell 4: 涌现阈值定量分析 ──────────────────────────────────────────────────
    md(
        "## Part 3：量化涌现阈值",
        "",
        "定义「涌现阈值」：任务成功率首次超过 50% 时对应的模型规模。",
        "步骤数越多，阈值越大——需要更大的模型才能「突然会了」。",
    ),
    code(
        "def find_emergence_threshold(log_scales, success_rates, threshold=0.5):",
        "    \"\"\"找到成功率首次超过 threshold 的位置（对数规模）\"\"\"",
        "    above = success_rates >= threshold",
        "    if not np.any(above):",
        "        return None",
        "    return log_scales[np.argmax(above)]",
        "",
        "print('步骤数  |  涌现阈值 log(N)  |  等效参数量')",
        "print('-' * 55)",
        "for n in range(1, 9):",
        "    rate = task_success_rate(log_scales, n)",
        "    threshold = find_emergence_threshold(log_scales, rate)",
        "    if threshold is not None:",
        "        equiv_params = np.exp(threshold)",
        "        print(f'  {n} 步   |     {threshold:6.2f}        |  {equiv_params:.2e} 参数')",
        "    else:",
        "        print(f'  {n} 步   |     未涌现（当前规模不够）')",
    ),

    # ── Cell 5: BIG-Bench 风格任务模拟 ────────────────────────────────────────────
    md(
        "## Part 4：BIG-Bench 风格——涌现 vs 平滑任务",
        "",
        "BIG-Bench 发现有些任务随规模平滑提升，有些任务则呈现涌现跳变。",
        "我们用模拟数据复现这两种模式。",
    ),
    code(
        "# 模拟 BIG-Bench 数据（参考 Wei et al. 2022 图2）",
        "model_sizes_b = np.array([0.5, 1, 2, 7, 13, 30, 70, 175])  # 单位：十亿参数",
        "log_sizes = np.log10(model_sizes_b)  # log10 坐标",
        "",
        "# 平滑任务：准确率随规模稳步提升（如情感分析）",
        "np.random.seed(42)",
        "smooth_task = 0.45 + 0.07 * log_sizes + np.random.normal(0, 0.02, len(log_sizes))",
        "smooth_task = np.clip(smooth_task, 0, 1)",
        "",
        "# 涌现任务：小模型接近随机，大模型突然跳升（如多步算术）",
        "emerge_task = np.where(",
        "    model_sizes_b < 20,",
        "    0.25 + np.random.normal(0, 0.03, len(model_sizes_b)),",
        "    0.75 + 0.04 * (np.log10(model_sizes_b) - np.log10(20)) + np.random.normal(0, 0.03, len(model_sizes_b))",
        ")",
        "emerge_task = np.clip(emerge_task, 0, 1)",
        "",
        "fig, axes = plt.subplots(1, 2, figsize=(13, 5))",
        "",
        "# 左图：平滑任务",
        "axes[0].semilogx(model_sizes_b, smooth_task, 'b-o', markersize=7, label='平滑任务（情感分析）')",
        "axes[0].axhline(0.25, color='gray', linestyle=':', alpha=0.5, label='随机基线（4选1）')",
        "axes[0].set_xlabel('模型参数量（十亿）')",
        "axes[0].set_ylabel('准确率')",
        "axes[0].set_title('平滑提升型任务')",
        "axes[0].set_ylim(0, 1)",
        "axes[0].legend()",
        "axes[0].grid(True, alpha=0.3)",
        "",
        "# 右图：涌现任务",
        "axes[1].semilogx(model_sizes_b, emerge_task, 'r-o', markersize=7, label='涌现型任务（多步算术）')",
        "axes[1].axhline(0.25, color='gray', linestyle=':', alpha=0.5, label='随机基线')",
        "axes[1].axvline(20, color='orange', linestyle='--', alpha=0.7, label='涌现阈值 ~20B')",
        "axes[1].set_xlabel('模型参数量（十亿）')",
        "axes[1].set_ylabel('准确率')",
        "axes[1].set_title('涌现型任务（BIG-Bench 风格）')",
        "axes[1].set_ylim(0, 1)",
        "axes[1].legend()",
        "axes[1].grid(True, alpha=0.3)",
        "",
        "plt.tight_layout()",
        f"plt.savefig(f'{ASSETS}/14-bigbench.png', dpi=100, bbox_inches='tight')",
        "plt.close()",
        "print('BIG-Bench 风格演示完成')",
    ),

    # ── Cell 6: Chain-of-Thought 涌现 ─────────────────────────────────────────────
    md(
        "## Part 5：Chain-of-Thought（思维链）涌现",
        "",
        "CoT 提示对小模型无效，对大模型有显著帮助——CoT 能力本身是涌现的。",
        "",
        "这里我们模拟一个简单场景：多步算术题，模型规模决定能否完成中间推理步骤。",
    ),
    code(
        "def simulate_cot_benefit(model_size_b, n_steps=3):",
        "    \"\"\"",
        "    模拟 CoT 提示的收益：",
        "    - 标准提示：直接预测答案，成功率 = 直接输出能力",
        "    - CoT 提示：先生成中间步骤，再给答案，成功率 = 各步的乘积（但每步精度更高）",
        "    返回 (standard_acc, cot_acc)",
        "    \"\"\"",
        "    log_s = np.log(model_size_b + 1e-6)",
        "    # 直接输出能力（sigmoid函数，在 ~20B 附近涌现）",
        "    direct_cap = sigmoid(log_s, k=0.8, x0=np.log(20))",
        "    # CoT 能力：每一步的准确率更高（模型能用草稿纠错），但需要模型足够大才支持",
        "    step_cap = sigmoid(log_s, k=1.2, x0=np.log(10))  # 每步准确率",
        "    cot_cap = step_cap ** n_steps  # n 步全对",
        "    # CoT 对小模型有害（生成乱步骤）：小于某阈值时，cot_cap < direct_cap",
        "    cot_helpful_threshold = 5.0  # 5B 以下 CoT 没帮助",
        "    if model_size_b < cot_helpful_threshold:",
        "        cot_acc = direct_cap * 0.8  # CoT 反而干扰",
        "    else:",
        "        cot_acc = cot_cap",
        "    return direct_cap, cot_acc",
        "",
        "sizes = np.logspace(-1, 2.5, 100)  # 0.1B 到 ~300B",
        "direct_accs = []",
        "cot_accs = []",
        "for s in sizes:",
        "    d, c = simulate_cot_benefit(s)",
        "    direct_accs.append(d)",
        "    cot_accs.append(c)",
        "",
        "direct_accs = np.array(direct_accs)",
        "cot_accs = np.array(cot_accs)",
        "",
        "plt.figure(figsize=(9, 5))",
        "plt.semilogx(sizes, direct_accs, 'b-', linewidth=2, label='标准提示（直接输出）')",
        "plt.semilogx(sizes, cot_accs, 'r-', linewidth=2, label='CoT 提示（思维链）')",
        "plt.axvline(5, color='gray', linestyle=':', alpha=0.7, label='5B：CoT 开始有帮助')",
        "plt.axvline(100, color='orange', linestyle=':', alpha=0.7, label='100B：CoT 显著领先')",
        "plt.xlabel('模型参数量（十亿）')",
        "plt.ylabel('任务准确率（模拟）')",
        "plt.title('Chain-of-Thought 涌现：大模型才能利用思维链')",
        "plt.legend()",
        "plt.grid(True, alpha=0.3)",
        "plt.ylim(0, 1)",
        f"plt.savefig(f'{ASSETS}/14-cot-emergence.png', dpi=100, bbox_inches='tight')",
        "plt.close()",
        "",
        "# 关键数字",
        "idx_5b = np.argmin(np.abs(sizes - 5))",
        "idx_100b = np.argmin(np.abs(sizes - 100))",
        "print(f'5B 模型：标准={direct_accs[idx_5b]:.2f}, CoT={cot_accs[idx_5b]:.2f}')",
        "print(f'100B 模型：标准={direct_accs[idx_100b]:.2f}, CoT={cot_accs[idx_100b]:.2f}')",
        "print('结论：CoT 对小模型无帮助（甚至有害），对大模型显著提升')",
    ),

    # ── Cell 7: GPT-4 vs GPT-3.5 数据对比 ────────────────────────────────────────
    md(
        "## Part 6：GPT-4 vs GPT-3.5 性能对比",
        "",
        "来自 GPT-4 技术报告（2023）的真实数据：",
        "以下几个专业考试的分数（各测试满分百分位）。",
    ),
    code(
        "# GPT-4 技术报告数据（百分位数，来自 OpenAI 2023）",
        "exams = ['律师资格 UBE', '医学执照 USMLE', 'GRE 语文', 'SAT 数学', 'AMC 10A 数学']",
        "gpt35_scores = [10, 53, 63, 70, 30]   # 近似值（百分位）",
        "gpt4_scores  = [90, 87, 99, 89, 60]   # 近似值（百分位）",
        "",
        "x_pos = np.arange(len(exams))",
        "width = 0.35",
        "",
        "fig, ax = plt.subplots(figsize=(11, 5))",
        "bars1 = ax.bar(x_pos - width/2, gpt35_scores, width, label='GPT-3.5', color='steelblue', alpha=0.8)",
        "bars2 = ax.bar(x_pos + width/2, gpt4_scores, width, label='GPT-4', color='tomato', alpha=0.8)",
        "",
        "ax.axhline(75, color='gray', linestyle='--', alpha=0.6, label='典型通过线 75%')",
        "ax.set_xlabel('考试类型')",
        "ax.set_ylabel('百分位数（相对于人类考生）')",
        "ax.set_title('GPT-4 vs GPT-3.5：专业考试对比（来源：GPT-4 技术报告）')",
        "ax.set_xticks(x_pos)",
        "ax.set_xticklabels(exams, rotation=15, ha='right')",
        "ax.legend()",
        "ax.set_ylim(0, 105)",
        "ax.grid(True, alpha=0.3, axis='y')",
        "",
        "# 在条形上方加数字",
        "for bar in bars1:",
        "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,",
        "            f'{bar.get_height():.0f}', ha='center', va='bottom', fontsize=9, color='steelblue')",
        "for bar in bars2:",
        "    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,",
        "            f'{bar.get_height():.0f}', ha='center', va='bottom', fontsize=9, color='tomato')",
        "",
        "plt.tight_layout()",
        f"plt.savefig(f'{ASSETS}/14-gpt4-vs-gpt35.png', dpi=100, bbox_inches='tight')",
        "plt.close()",
        "print('数据来源：OpenAI GPT-4 Technical Report (2023), arXiv:2303.08774')",
        "print('注：上述数据为报告中的近似值，具体分数见原报告 Table 1')",
    ),

    # ── Cell 8: 涌现争议——Schaeffer 2023 ──────────────────────────────────────────
    md(
        "## Part 7：涌现的争议——真的「突然会了」吗？",
        "",
        "Schaeffer et al. 2023 提出：涌现可能是**测量方式**的产物。",
        "用离散指标（对/错）会看到跳变；用连续指标（损失/概率）可能是平滑的。",
    ),
    code(
        "# 演示：同样的模型，不同指标看到不同形态",
        "log_scales_demo = np.linspace(0, 8, 200)",
        "",
        "# 真实能力：平滑线性提升（对数坐标）",
        "true_logit = -3 + 0.8 * log_scales_demo  # 对数几率线性增长",
        "true_prob = 1 / (1 + np.exp(-true_logit))  # 对应的概率（平滑S形）",
        "",
        "# 离散指标：需要概率 > 0.5 才算「对」",
        "discrete_correct = (true_prob > 0.5).astype(float)",
        "",
        "# 多题平均准确率（离散，但平均后仍然有跳变外观）",
        "n_questions = 10",
        "np.random.seed(123)",
        "avg_correct = np.array([",
        "    np.mean(np.random.binomial(1, p, n_questions))",
        "    for p in true_prob",
        "])",
        "",
        "fig, axes = plt.subplots(1, 3, figsize=(15, 4))",
        "",
        "# 左：连续指标（概率）——平滑",
        "axes[0].plot(log_scales_demo, true_prob, 'b-', linewidth=2)",
        "axes[0].set_xlabel('log(模型规模)')",
        "axes[0].set_ylabel('答对概率（连续）')",
        "axes[0].set_title('连续指标：平滑增长')",
        "axes[0].grid(True, alpha=0.3)",
        "",
        "# 中：离散指标（单题对错）——二值跳变",
        "axes[1].plot(log_scales_demo, discrete_correct, 'r-', linewidth=2)",
        "axes[1].set_xlabel('log(模型规模)')",
        "axes[1].set_ylabel('是否答对（0或1）')",
        "axes[1].set_title('离散指标（单题）：突然跳变')",
        "axes[1].grid(True, alpha=0.3)",
        "",
        "# 右：10题平均——介于两者之间",
        "axes[2].plot(log_scales_demo, avg_correct, 'g-', linewidth=2)",
        "axes[2].set_xlabel('log(模型规模)')",
        "axes[2].set_ylabel('平均准确率（10题）')",
        "axes[2].set_title('平均准确率：S 形，看起来像涌现')",
        "axes[2].grid(True, alpha=0.3)",
        "",
        "plt.suptitle('Schaeffer 2023：测量方式决定你看到什么规律', fontsize=12, fontweight='bold')",
        "plt.tight_layout()",
        f"plt.savefig(f'{ASSETS}/14-schaeffer.png', dpi=100, bbox_inches='tight')",
        "plt.close()",
        "print('结论：涌现现象的争议在于——底层能力是平滑的，跳变来自离散测量方式')",
        "print('这并不否定涌现现象，但提醒我们：指标选择影响结论')",
    ),

    # ── Cell 9: 综合汇总 ──────────────────────────────────────────────────────────
    md(
        "## Part 8：今天学到了什么",
        "",
        "| 概念 | 数学本质 | 工程意义 |",
        "|------|---------|---------|",
        "| 涌现能力 | 多步骤成功率相乘 → S形跳变 | 小模型不能按比例缩小大模型能力 |",
        "| BIG-Bench | 选涌现型任务测大模型边界 | 评估指标选择影响结论 |",
        "| CoT 涌现 | 草稿需要足够大的工作记忆 | 提示词对小模型效果有限 |",
        "| Schaeffer 争议 | 连续vs离散指标看到不同规律 | 涌现存在，但可能被放大 |",
        "",
        "**GPT-4 的核心贡献**：",
        "- 更长上下文 → 支持复杂多步推理",
        "- 更强 RLHF → 更少有害输出",
        "- 多模态 → 图像理解",
        "",
        "**局限（引出下一节点）**：",
        "- 推理成本高（每次推理昂贵）",
        "- 知识截止固定",
        "- 仍有幻觉",
        "→ 引出：RAG（检索增强生成）、蒸馏、推理效率优化……",
    ),
    code(
        "# 最终验证：所有核心图表都生成了",
        "import os",
        "assets_dir = '../docs/assets'",
        "expected_files = [",
        "    '14-sigmoid.png',",
        "    '14-emergence-steps.png',",
        "    '14-bigbench.png',",
        "    '14-cot-emergence.png',",
        "    '14-gpt4-vs-gpt35.png',",
        "    '14-schaeffer.png',",
        "]",
        "missing = [f for f in expected_files if not os.path.exists(os.path.join(assets_dir, f))]",
        "if missing:",
        "    print('缺少图表：', missing)",
        "else:",
        "    print('全部图表已生成 ✓')",
        "",
        "# 核心数值验证",
        "threshold_1step = find_emergence_threshold(log_scales, task_success_rate(log_scales, 1))",
        "threshold_5step = find_emergence_threshold(log_scales, task_success_rate(log_scales, 5))",
        "print(f'1 步任务涌现阈值：log(N) = {threshold_1step:.2f}')",
        "print(f'5 步任务涌现阈值：log(N) = {threshold_5step:.2f}')",
        "print(f'步骤从 1→5，涌现阈值增加了 {threshold_5step - threshold_1step:.2f}')",
    ),
]

notebook = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "cells": cells,
}

NB_PATH.parent.mkdir(parents=True, exist_ok=True)
with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(notebook, f, ensure_ascii=False, indent=1)

print(f"Written: {NB_PATH}  ({len(cells)} cells)")
