#!/usr/bin/env python3
# gen_nb_09.py -- generate notebooks/09-gpt2-2019.ipynb
import json, pathlib

cells = []

def code(src): return {'cell_type': 'code', 'execution_count': None, 'metadata': {}, 'outputs': [], 'source': src}
def md(src): return {'cell_type': 'markdown', 'metadata': {}, 'source': src}

# -- Cell 0: Setup -------------------------------------------------------
cells.append(code(
    'import numpy as np\n'
    'import matplotlib\n'
    'matplotlib.rcParams["font.family"] = "DejaVu Sans"\n'
    'import matplotlib.pyplot as plt\n'
    'import warnings\n'
    'warnings.filterwarnings("ignore")\n'
    'np.random.seed(42)\n'
    'print("Setup complete")'
))

# -- Cell 1: Causal Mask -------------------------------------------------
cells.append(md(
    '## Step 1: Causal Mask\n\n'
    'GPT-2 is a **decoder-only** model. Unlike BERT, it generates text from left to right\n'
    'and must **never look at future tokens** during training.\n\n'
    'We enforce this with a **causal mask**: a lower-triangular matrix of 1s and 0s.\n'
    'Position `i` can only attend to positions `0 ... i` (itself and everything before it).\n\n'
    '```\n'
    'For seq_len=4:\n'
    '  [[1, 0, 0, 0],\n'
    '   [1, 1, 0, 0],\n'
    '   [1, 1, 1, 0],\n'
    '   [1, 1, 1, 1]]\n'
    '```\n\n'
    'Positions with 0 are set to -infinity before softmax, so their attention weight becomes ~0.'
))

cells.append(code(
    'def make_causal_mask(seq_len):\n'
    '    """Lower-triangular mask: 1 = can attend, 0 = blocked."""\n'
    '    return np.tril(np.ones((seq_len, seq_len), dtype=np.float32))\n'
    '\n'
    'seq_len = 6\n'
    'mask = make_causal_mask(seq_len)\n'
    '\n'
    'fig, ax = plt.subplots(figsize=(4, 4))\n'
    'ax.imshow(mask, cmap="Blues", vmin=0, vmax=1)\n'
    'ax.set_title(f"Causal Mask ({seq_len}x{seq_len})")\n'
    'ax.set_xlabel("Key position (attended to)")\n'
    'ax.set_ylabel("Query position")\n'
    'for i in range(seq_len):\n'
    '    for j in range(seq_len):\n'
    '        ax.text(j, i, int(mask[i, j]), ha="center", va="center",\n'
    '                color="white" if mask[i, j] == 1 else "gray", fontsize=10)\n'
    'plt.tight_layout()\n'
    'plt.savefig("../figures/09_causal_mask.png", dpi=100, bbox_inches="tight")\n'
    'plt.show()\n'
    '\n'
    'print("Causal mask shape:", mask.shape)\n'
    'print("Row 0 (first token): can only attend to position 0 =", mask[0])\n'
    'print("Row 3 (4th token):   can attend to positions 0-3  =", mask[3])\n'
    'print("Is lower triangular:", np.allclose(mask, np.tril(mask)))'
))

# -- Cell 2: Causal Attention --------------------------------------------
cells.append(md(
    '## Step 2: Causal Self-Attention\n\n'
    'Scaled dot-product attention with the causal mask applied:\n\n'
    '1. Compute scores: `scores = Q @ K.T / sqrt(d_k)`\n'
    '2. **Apply mask**: set positions where `mask == 0` to `-1e9` (near -infinity)\n'
    '3. Softmax over keys\n'
    '4. Weighted sum of values\n\n'
    'This is the core building block of every GPT-style model.'
))

cells.append(code(
    'def softmax(x, axis=-1):\n'
    '    x = x - x.max(axis=axis, keepdims=True)  # numerical stability\n'
    '    e = np.exp(x)\n'
    '    return e / e.sum(axis=axis, keepdims=True)\n'
    '\n'
    'def causal_attention(Q, K, V, mask):\n'
    '    """\n'
    '    Q, K, V: (seq_len, d_k)\n'
    '    mask:    (seq_len, seq_len) -- 1=attend, 0=block\n'
    '    Returns: (seq_len, d_k)\n'
    '    """\n'
    '    d_k = Q.shape[-1]\n'
    '    scores = Q @ K.T / np.sqrt(d_k)          # (seq_len, seq_len)\n'
    '    scores = scores + (1.0 - mask) * -1e9    # apply causal mask\n'
    '    weights = softmax(scores, axis=-1)        # (seq_len, seq_len)\n'
    '    return weights @ V, weights               # (seq_len, d_k)\n'
    '\n'
    '# Small example: seq_len=4, d_k=8\n'
    'np.random.seed(0)\n'
    'SL, DK = 4, 8\n'
    'Q = np.random.randn(SL, DK)\n'
    'K = np.random.randn(SL, DK)\n'
    'V = np.random.randn(SL, DK)\n'
    'mask = make_causal_mask(SL)\n'
    '\n'
    'out, attn_weights = causal_attention(Q, K, V, mask)\n'
    '\n'
    'print("Output shape:", out.shape)\n'
    'print()\n'
    'print("Attention weight matrix (rows=query, cols=key):")\n'
    'print(np.round(attn_weights, 3))\n'
    'print()\n'
    'print("Upper triangle should be ~0 (future tokens blocked):")\n'
    'upper = attn_weights[np.triu_indices(SL, k=1)]\n'
    'print("  Max upper-triangle weight:", upper.max().round(8))\n'
    'print("  Rows sum to 1:", np.allclose(attn_weights.sum(axis=-1), 1.0))'
))

# -- Cell 3: BPE Demo ----------------------------------------------------
cells.append(md(
    '## Step 3: Byte Pair Encoding (BPE)\n\n'
    'GPT-2 uses **Byte Pair Encoding** to tokenize text — no out-of-vocabulary words!\n\n'
    'The idea is simple:\n'
    '1. Start with characters as your vocabulary\n'
    '2. Count all adjacent character pairs in the corpus\n'
    '3. Merge the **most frequent** pair into a new token\n'
    '4. Repeat until you reach your desired vocabulary size\n\n'
    'Example: `"low lower newest"` → after merges, `"low"` becomes a single token.\n\n'
    'GPT-2 uses 50,257 BPE tokens. We simulate the merging process on a tiny corpus.'
))

cells.append(code(
    '# Pure-Python BPE merge demo (no external libraries)\n'
    '\n'
    'def get_vocab(corpus):\n'
    '    """Split corpus into word -> char-tuple frequency dict."""\n'
    '    from collections import Counter\n'
    '    vocab = Counter()\n'
    '    for word in corpus.split():\n'
    '        # Represent each word as a tuple of characters + end-of-word symbol\n'
    '        chars = tuple(list(word) + ["</w>"])\n'
    '        vocab[chars] += 1\n'
    '    return vocab\n'
    '\n'
    'def get_pair_counts(vocab):\n'
    '    """Count frequency of every adjacent symbol pair."""\n'
    '    from collections import Counter\n'
    '    pairs = Counter()\n'
    '    for symbols, freq in vocab.items():\n'
    '        for i in range(len(symbols) - 1):\n'
    '            pairs[(symbols[i], symbols[i + 1])] += freq\n'
    '    return pairs\n'
    '\n'
    'def merge_pair(pair, vocab):\n'
    '    """Merge all occurrences of `pair` in vocab into a single token."""\n'
    '    new_vocab = {}\n'
    '    bigram = pair[0] + pair[1]  # merged token string\n'
    '    for symbols, freq in vocab.items():\n'
    '        new_syms = []\n'
    '        i = 0\n'
    '        while i < len(symbols):\n'
    '            if i < len(symbols) - 1 and symbols[i] == pair[0] and symbols[i+1] == pair[1]:\n'
    '                new_syms.append(bigram)\n'
    '                i += 2\n'
    '            else:\n'
    '                new_syms.append(symbols[i])\n'
    '                i += 1\n'
    '        new_vocab[tuple(new_syms)] = freq\n'
    '    return new_vocab\n'
    '\n'
    '# Tiny corpus\n'
    'corpus = "low low low lower lower newest newest highest"\n'
    'vocab = get_vocab(corpus)\n'
    '\n'
    'print("=== Initial vocabulary ===")\n'
    'for word, freq in sorted(vocab.items(), key=lambda x: -x[1]):\n'
    '    print(f"  {list(word)}  (x{freq})")\n'
    '\n'
    'print()\n'
    'NUM_MERGES = 8\n'
    'merges = []\n'
    'for step in range(NUM_MERGES):\n'
    '    pairs = get_pair_counts(vocab)\n'
    '    if not pairs:\n'
    '        break\n'
    '    best = max(pairs, key=pairs.get)\n'
    '    merges.append(best)\n'
    '    vocab = merge_pair(best, vocab)\n'
    '    print(f"Merge {step+1}: {best[0]!r} + {best[1]!r} -> {best[0]+best[1]!r}  (freq={pairs[best]})")\n'
    '\n'
    'print()\n'
    'print("=== Vocabulary after BPE merges ===")\n'
    'for word, freq in sorted(vocab.items(), key=lambda x: -x[1]):\n'
    '    print(f"  {list(word)}  (x{freq})")'
))

# -- Cell 4: Mini GPT Block ----------------------------------------------
cells.append(md(
    '## Step 4: Mini GPT Block\n\n'
    'A single GPT-2 transformer block applies these steps in order:\n\n'
    '1. **Pre-LayerNorm** (applied BEFORE attention, unlike original Transformer which uses post-LN)\n'
    '2. **Causal self-attention** (with residual connection)\n'
    '3. **Pre-LayerNorm** again\n'
    '4. **FFN with GELU activation** (with residual connection)\n\n'
    'GPT-2\'s switch to Pre-LN makes training more stable. The model stacks 12-48 of these blocks.\n\n'
    'GELU ("Gaussian Error Linear Unit") is smoother than ReLU and works better for language:\n'
    '`GELU(x) ≈ 0.5 * x * (1 + tanh(sqrt(2/pi) * (x + 0.044715 * x^3)))`'
))

cells.append(code(
    'def layer_norm(x, eps=1e-5):\n'
    '    """Normalize across the last dimension."""\n'
    '    mean = x.mean(axis=-1, keepdims=True)\n'
    '    std  = x.std(axis=-1,  keepdims=True)\n'
    '    return (x - mean) / (std + eps)\n'
    '\n'
    'def gelu(x):\n'
    '    """GELU approximation used in GPT-2."""\n'
    '    return 0.5 * x * (1 + np.tanh(np.sqrt(2 / np.pi) * (x + 0.044715 * x**3)))\n'
    '\n'
    'def gpt_block(x, W_qkv, W_proj, W_ff1, W_ff2):\n'
    '    """\n'
    '    One GPT-2 transformer block.\n'
    '\n'
    '    x:      (seq_len, d_model)\n'
    '    W_qkv:  (d_model, 3*d_model)  -- fused QKV projection\n'
    '    W_proj: (d_model, d_model)    -- output projection\n'
    '    W_ff1:  (d_model, 4*d_model)  -- FFN expand\n'
    '    W_ff2:  (4*d_model, d_model)  -- FFN contract\n'
    '\n'
    '    Returns: (seq_len, d_model)\n'
    '    """\n'
    '    seq_len, d_model = x.shape\n'
    '\n'
    '    # --- Pre-LayerNorm + Causal Self-Attention ---\n'
    '    x_norm = layer_norm(x)                           # pre-LN\n'
    '    qkv = x_norm @ W_qkv                            # (seq_len, 3*d_model)\n'
    '    Q, K, V = np.split(qkv, 3, axis=-1)             # each (seq_len, d_model)\n'
    '    mask = make_causal_mask(seq_len)\n'
    '    attn_out, _ = causal_attention(Q, K, V, mask)\n'
    '    attn_out = attn_out @ W_proj                    # (seq_len, d_model)\n'
    '    x = x + attn_out                                # residual\n'
    '\n'
    '    # --- Pre-LayerNorm + FFN ---\n'
    '    x_norm2 = layer_norm(x)                         # pre-LN\n'
    '    ff_hidden = gelu(x_norm2 @ W_ff1)               # (seq_len, 4*d_model)\n'
    '    ff_out = ff_hidden @ W_ff2                       # (seq_len, d_model)\n'
    '    x = x + ff_out                                  # residual\n'
    '\n'
    '    return x\n'
    '\n'
    '# --- Demo forward pass ---\n'
    'np.random.seed(7)\n'
    'D = 16      # d_model (toy)\n'
    'SEQ = 5     # sequence length\n'
    'scale = 0.02\n'
    '\n'
    'x_in   = np.random.randn(SEQ, D) * scale\n'
    'W_qkv  = np.random.randn(D, 3 * D) * scale\n'
    'W_proj = np.random.randn(D, D)     * scale\n'
    'W_ff1  = np.random.randn(D, 4 * D) * scale\n'
    'W_ff2  = np.random.randn(4 * D, D) * scale\n'
    '\n'
    'x_out = gpt_block(x_in, W_qkv, W_proj, W_ff1, W_ff2)\n'
    '\n'
    'print("GPT Block demo")\n'
    'print("  Input  shape:", x_in.shape,  "(seq_len=%d, d_model=%d)" % (SEQ, D))\n'
    'print("  Output shape:", x_out.shape, "(same -- residual stream preserved)")\n'
    'print()\n'
    'print("GELU vs ReLU comparison on [-3, 3]:")\n'
    'xs = np.linspace(-3, 3, 7)\n'
    'print("  x    :", xs.round(1))\n'
    'print("  gelu :", gelu(xs).round(3))\n'
    'print("  relu :", np.maximum(0, xs).round(3))\n'
    'print()\n'
    'print("Note: GELU is smooth near 0 (small negative values pass through slightly)")'
))

# -- Cell 5: Greedy Decoding + Temperature Sampling ----------------------
cells.append(md(
    '## Step 5: Greedy Decoding & Temperature Sampling\n\n'
    'After the GPT-2 block(s) produce hidden states, a linear head projects to **logits** over the vocabulary.\n'
    'The model then picks the next token.\n\n'
    '**Greedy decoding**: always pick `argmax(logits)`. Deterministic but can be repetitive.\n\n'
    '**Temperature sampling**: divide logits by a temperature `T` before softmax.\n'
    '- `T → 0`: more deterministic (sharp distribution)\n'
    '- `T = 1`: use the raw model distribution\n'
    '- `T > 1`: more random (flatter distribution)\n\n'
    'Temperature controls the creativity vs. coherence trade-off.'
))

cells.append(code(
    'def greedy_decode(logits):\n'
    '    """Return the token with the highest logit."""\n'
    '    return int(np.argmax(logits))\n'
    '\n'
    'def temperature_sample(logits, temperature=1.0, rng=None):\n'
    '    """\n'
    '    Sample from softmax(logits / temperature).\n'
    '    temperature -> 0: greedy\n'
    '    temperature -> inf: uniform random\n'
    '    """\n'
    '    if rng is None:\n'
    '        rng = np.random.default_rng(42)\n'
    '    scaled = logits / max(temperature, 1e-10)\n'
    '    probs = softmax(scaled)\n'
    '    return int(rng.choice(len(probs), p=probs))\n'
    '\n'
    '# Toy vocabulary of 8 tokens\n'
    'toy_vocab = ["the", "cat", "sat", "on", "mat", "dog", "ran", "fast"]\n'
    'TVOCAB = len(toy_vocab)\n'
    '\n'
    '# Simulate logits from the model (one position)\n'
    'np.random.seed(3)\n'
    'logits = np.array([0.1, 3.5, 0.8, 0.2, 1.0, 0.5, 2.1, 0.3])  # hand-crafted\n'
    '\n'
    'print("Toy vocabulary:", toy_vocab)\n'
    'print("Logits:", logits)\n'
    'print()\n'
    '\n'
    'greedy_tok = greedy_decode(logits)\n'
    'print(f"Greedy decode -> token {greedy_tok} = \'{toy_vocab[greedy_tok]}\'")\n'
    'print()\n'
    '\n'
    'rng = np.random.default_rng(42)\n'
    'temperatures = [0.01, 0.5, 1.0, 2.0]\n'
    'print("Temperature sampling (10 samples each):")\n'
    'for T in temperatures:\n'
    '    probs = softmax(logits / T)\n'
    '    samples = [toy_vocab[temperature_sample(logits, T, rng)] for _ in range(10)]\n'
    '    top = toy_vocab[np.argmax(probs)]\n'
    '    print(f"  T={T:.2f} | top-token={top!r:6s} | samples: {samples}")\n'
    '\n'
    'print()\n'
    '# Visualize probability distributions at different temperatures\n'
    'fig, axes = plt.subplots(1, 4, figsize=(14, 3), sharey=False)\n'
    'for ax, T in zip(axes, temperatures):\n'
    '    probs = softmax(logits / T)\n'
    '    ax.bar(range(TVOCAB), probs, color="steelblue")\n'
    '    ax.set_xticks(range(TVOCAB))\n'
    '    ax.set_xticklabels(toy_vocab, rotation=45, ha="right", fontsize=8)\n'
    '    ax.set_title(f"T = {T}")\n'
    '    ax.set_ylabel("Probability" if T == 0.01 else "")\n'
    '    ax.set_ylim(0, 1)\n'
    'fig.suptitle("Effect of Temperature on Token Probabilities", fontsize=12)\n'
    'plt.tight_layout()\n'
    'plt.savefig("../figures/09_temperature.png", dpi=100, bbox_inches="tight")\n'
    'plt.show()\n'
    'print("Saved temperature plot.")'
))

# -- Cell 6: Scaling Laws Visualization ----------------------------------
cells.append(md(
    '## Step 6: Scaling Laws\n\n'
    'In 2020, OpenAI published "Scaling Laws for Neural Language Models" (Kaplan et al.).\n'
    'They found that validation loss follows a **power law** with compute:\n\n'
    '`L(C) ≈ (C_min / C)^0.048`\n\n'
    'On a **log-log plot**, this becomes a straight line:\n'
    '`log(L) = const - 0.048 * log(C)`\n\n'
    'This discovery was fundamental to the decision to scale up to GPT-3 (175B params) and beyond.\n'
    'More compute = lower loss, predictably and reliably.'
))

cells.append(code(
    '# Simulate the scaling law: L(C) = a * C^(-alpha)\n'
    'alpha = 0.048   # exponent from Kaplan et al. 2020\n'
    'a     = 3.1     # normalization constant (arbitrary for illustration)\n'
    '\n'
    '# Compute budget range: 1e17 to 1e23 FLOPs (rough GPT-2 to GPT-3 range)\n'
    'C = np.logspace(17, 23, 200)   # 200 points on log scale\n'
    'L = a * (C ** (-alpha))        # power law loss\n'
    '\n'
    '# Add a few annotated reference points\n'
    'ref_compute = np.array([1e18, 1e20, 1e22])\n'
    'ref_loss    = a * (ref_compute ** (-alpha))\n'
    'ref_labels  = ["GPT-2 small\\n~1.5B FLOPs", "GPT-2 XL\\n~100B FLOPs", "GPT-3\\n~10T FLOPs"]\n'
    '\n'
    'fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))\n'
    '\n'
    '# Left: linear scale\n'
    'ax1.plot(C, L, color="royalblue", linewidth=2)\n'
    'ax1.scatter(ref_compute, ref_loss, color="orangered", zorder=5, s=80)\n'
    'ax1.set_xlabel("Compute (FLOPs)")\n'
    'ax1.set_ylabel("Validation Loss")\n'
    'ax1.set_title("Scaling Law (linear scale)")\n'
    'ax1.ticklabel_format(style="sci", axis="x", scilimits=(0,0))\n'
    '\n'
    '# Right: log-log scale -- should look like a straight line\n'
    'ax2.loglog(C, L, color="royalblue", linewidth=2, label=f"L = {a} * C^(-{alpha})")\n'
    'ax2.scatter(ref_compute, ref_loss, color="orangered", zorder=5, s=80)\n'
    'for xr, yr, lbl in zip(ref_compute, ref_loss, ref_labels):\n'
    '    ax2.annotate(lbl, xy=(xr, yr), xytext=(xr*3, yr*1.05),\n'
    '                 fontsize=7, arrowprops=dict(arrowstyle="->", lw=0.8))\n'
    'ax2.set_xlabel("Compute (FLOPs)  [log scale]")\n'
    'ax2.set_ylabel("Validation Loss  [log scale]")\n'
    'ax2.set_title("Scaling Law (log-log scale) -- straight line!")\n'
    'ax2.legend(fontsize=8)\n'
    '\n'
    'plt.suptitle("Neural Scaling Laws (Kaplan et al. 2020)", fontsize=13)\n'
    'plt.tight_layout()\n'
    'plt.savefig("../figures/09_scaling_laws.png", dpi=100, bbox_inches="tight")\n'
    'plt.show()\n'
    '\n'
    'print("Scaling law: L(C) = %.1f * C^(-%.3f)" % (a, alpha))\n'
    'print()\n'
    'print("Predicted losses at reference compute:")\n'
    'for xr, yr, lbl in zip(ref_compute, ref_loss, ref_labels):\n'
    '    label_short = lbl.split("\\n")[0]\n'
    '    print(f"  {label_short:12s} C={xr:.0e}  ->  L={yr:.4f}")\n'
    'print()\n'
    'print("Key insight: on a log-log plot the power law is a straight line.")\n'
    'print("This means doubling compute ALWAYS reduces loss by the same fraction.")\n'
    'print("Slope =", -alpha, "(negative = more compute -> lower loss)")'
))

# -- End: write notebook --------------------------------------------------
out = pathlib.Path(__file__).parent.parent / 'notebooks' / '09-gpt2-2019.ipynb'
nb = {
    'nbformat': 4,
    'nbformat_minor': 5,
    'metadata': {'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'}, 'language_info': {'name': 'python', 'version': '3.8.0'}},
    'cells': cells,
}
out.write_text(json.dumps(nb, ensure_ascii=False, indent=1))
print(f"Written {out}")
