"""Generate notebooks/06-attention-2015.ipynb — Attention Mechanism (Bahdanau 2015)."""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NB_PATH = os.path.join(ROOT, "notebooks", "06-attention-2015.ipynb")


def cell(cell_type, source, outputs=None):
    if cell_type == "markdown":
        return {"cell_type": "markdown", "metadata": {}, "source": source}
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": outputs or [],
        "source": source,
    }


cells = [
    # ── Cell 0: Title ─────────────────────────────────────────────────────────
    cell("markdown", [
        "# 节点06：Attention 机制（Bahdanau 2015）\n",
        "\n",
        "**目标**：从零实现加性注意力（Additive Attention），理解它如何解决 Seq2Seq 的信息瓶颈。\n",
        "\n",
        "**依赖**：`numpy`、`matplotlib`（可选 `torch`）\n",
    ]),

    # ── Cell 1: Setup ──────────────────────────────────────────────────────────
    cell("code", [
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "import matplotlib\n",
        "\n",
        "np.random.seed(42)\n",
        "matplotlib.rcParams['font.family'] = ['DejaVu Sans']\n",
    ]),

    # ── Cell 2: Information Bottleneck Demo ───────────────────────────────────
    cell("markdown", [
        "## 1. 信息瓶颈演示\n",
        "\n",
        "传统 Seq2Seq 把所有信息压缩进一个固定大小向量 $c$。\n",
        "我们用一个极简 RNN 来演示：随着序列变长，最终隐状态承载的\"有效信息\"会越来越少。\n",
    ]),
    cell("code", [
        "def simple_rnn_step(h, x, W_h, W_x, b):\n",
        "    return np.tanh(W_h @ h + W_x @ x + b)\n",
        "\n",
        "hidden_size = 4\n",
        "input_size = 4\n",
        "W_h = np.random.randn(hidden_size, hidden_size) * 0.5\n",
        "W_x = np.random.randn(hidden_size, input_size) * 0.5\n",
        "b = np.zeros(hidden_size)\n",
        "\n",
        "# 用不同长度的序列，观察最终隐状态的方差（信息丰富度的代理指标）\n",
        "seq_lengths = [1, 2, 4, 8, 16, 32, 64]\n",
        "final_h_vars = []\n",
        "\n",
        "for seq_len in seq_lengths:\n",
        "    trials = []\n",
        "    for _ in range(100):  # 100 次随机序列\n",
        "        xs = np.random.randn(seq_len, input_size)\n",
        "        h = np.zeros(hidden_size)\n",
        "        for x in xs:\n",
        "            h = simple_rnn_step(h, x, W_h, W_x, b)\n",
        "        trials.append(h)\n",
        "    # 不同序列的最终 h 方差（越小说明越\"压缩\"到固定范围，信息差异消失）\n",
        "    final_h_vars.append(np.var(np.stack(trials), axis=0).mean())\n",
        "\n",
        "plt.figure(figsize=(7, 3))\n",
        "plt.plot(seq_lengths, final_h_vars, 'o-', color='steelblue')\n",
        "plt.xlabel('序列长度')\n",
        "plt.ylabel('最终隐状态方差（不同输入序列之间）')\n",
        "plt.title('信息瓶颈：序列越长，最终 h 越趋同（区分度下降）')\n",
        "plt.grid(True, alpha=0.3)\n",
        "plt.tight_layout()\n",
        "plt.savefig('../docs/assets/06_bottleneck.png', dpi=100)\n",
        "plt.show()\n",
        "print('方差随序列长度变化：', [f'{v:.4f}' for v in final_h_vars])\n",
    ]),

    # ── Cell 3: Attention Core Implementation ────────────────────────────────
    cell("markdown", [
        "## 2. 手撕 Bahdanau 加性注意力\n",
        "\n",
        "三步：**对齐分数 → Softmax → Context Vector**\n",
        "\n",
        "$$e_{ij} = \\mathbf{v}^T \\tanh(\\mathbf{W}_a \\mathbf{s}_{i-1} + \\mathbf{U}_a \\mathbf{h}_j)$$\n",
        "\n",
        "$$\\alpha_{ij} = \\text{softmax}(e_{ij})$$\n",
        "\n",
        "$$\\mathbf{c}_i = \\sum_j \\alpha_{ij} \\cdot \\mathbf{h}_j$$\n",
    ]),
    cell("code", [
        "def softmax(x):\n",
        "    \"\"\"数值稳定版 softmax：先减去最大值，防止指数溢出。\"\"\"\n",
        "    x_shifted = x - np.max(x)\n",
        "    e = np.exp(x_shifted)\n",
        "    return e / e.sum()\n",
        "\n",
        "\n",
        "class BahdanauAttention:\n",
        "    \"\"\"加性注意力（Bahdanau 2015）。\n",
        "    \n",
        "    参数:\n",
        "        encoder_size: 编码器隐状态维度\n",
        "        decoder_size: 解码器隐状态维度\n",
        "        attn_size:    对齐网络的中间维度\n",
        "    \"\"\"\n",
        "    def __init__(self, encoder_size, decoder_size, attn_size):\n",
        "        # 学习到的参数（实际训练时通过梯度更新；这里随机初始化用于演示）\n",
        "        self.W_a = np.random.randn(attn_size, decoder_size) * 0.1\n",
        "        self.U_a = np.random.randn(attn_size, encoder_size) * 0.1\n",
        "        self.v = np.random.randn(attn_size) * 0.1\n",
        "\n",
        "    def alignment_scores(self, s_prev, encoder_states):\n",
        "        \"\"\"计算对齐分数 e_j for j in 0..T-1.\n",
        "        \n",
        "        Args:\n",
        "            s_prev:         解码器上一步隐状态，形状 (decoder_size,)\n",
        "            encoder_states: 编码器所有隐状态，形状 (T, encoder_size)\n",
        "        Returns:\n",
        "            scores: 形状 (T,)\n",
        "        \"\"\"\n",
        "        T = encoder_states.shape[0]\n",
        "        # W_a @ s_prev: (attn_size,)  — 与 T 无关，广播\n",
        "        dec_part = self.W_a @ s_prev  # (attn_size,)\n",
        "        scores = np.zeros(T)\n",
        "        for j in range(T):\n",
        "            enc_part = self.U_a @ encoder_states[j]  # (attn_size,)\n",
        "            scores[j] = self.v @ np.tanh(dec_part + enc_part)\n",
        "        return scores\n",
        "\n",
        "    def forward(self, s_prev, encoder_states):\n",
        "        \"\"\"完整的注意力前向传播。\n",
        "        \n",
        "        Returns:\n",
        "            context: 形状 (encoder_size,)\n",
        "            alpha:   注意力权重，形状 (T,)\n",
        "        \"\"\"\n",
        "        scores = self.alignment_scores(s_prev, encoder_states)\n",
        "        alpha = softmax(scores)               # (T,)\n",
        "        context = alpha @ encoder_states       # (encoder_size,)\n",
        "        return context, alpha\n",
        "\n",
        "\n",
        "# ── 快速测试 ──────────────────────────────────────────────────────────────────\n",
        "enc_size, dec_size, attn_size = 8, 6, 10\n",
        "T = 5  # 编码器序列长度\n",
        "\n",
        "attn = BahdanauAttention(enc_size, dec_size, attn_size)\n",
        "encoder_states = np.random.randn(T, enc_size)\n",
        "s_prev = np.random.randn(dec_size)\n",
        "\n",
        "context, alpha = attn.forward(s_prev, encoder_states)\n",
        "\n",
        "print(f'encoder_states: {encoder_states.shape}')\n",
        "print(f's_prev:         {s_prev.shape}')\n",
        "print(f'context:        {context.shape}')\n",
        "print(f'alpha (sum={alpha.sum():.4f}): {alpha.round(4)}')\n",
        "assert alpha.shape == (T,), 'alpha 形状错误'\n",
        "assert abs(alpha.sum() - 1.0) < 1e-9, 'alpha 不是概率分布'\n",
        "assert context.shape == (enc_size,), 'context 形状错误'\n",
        "print('✓ 形状验证通过')\n",
    ]),

    # ── Cell 4: Softmax Properties ───────────────────────────────────────────
    cell("markdown", [
        "## 3. Softmax 性质验证\n",
        "\n",
        "Softmax 有两个关键性质：\n",
        "1. **非负**：所有输出 ≥ 0\n",
        "2. **归一**：所有输出之和 = 1\n"
    ]),
    cell("code", [
        "# 验证数值稳定性：即使输入很大也不溢出\n",
        "large_input = np.array([1000.0, 1001.0, 999.0])\n",
        "result = softmax(large_input)\n",
        "print(f'大数值输入: {large_input}')\n",
        "print(f'Softmax 输出: {result.round(4)}')\n",
        "print(f'输出之和: {result.sum():.6f}')\n",
        "assert np.all(result >= 0), '输出有负值'\n",
        "assert abs(result.sum() - 1.0) < 1e-9, '输出之和不为 1'\n",
        "\n",
        "# 一个直觉演示：不同\"尖锐度\"的分数\n",
        "fig, axes = plt.subplots(1, 3, figsize=(10, 3))\n",
        "base_scores = np.array([0.5, 1.0, 3.0, 0.8, 0.3])\n",
        "for ax, scale in zip(axes, [0.5, 1.0, 3.0]):\n",
        "    weights = softmax(base_scores * scale)\n",
        "    ax.bar(range(5), weights, color='steelblue', alpha=0.8)\n",
        "    ax.set_title(f'分数放大倍数 = {scale}')\n",
        "    ax.set_ylim(0, 1)\n",
        "    ax.set_xlabel('输入位置 j')\n",
        "    ax.set_ylabel('α_j')\n",
        "plt.suptitle('放大对齐分数 -> 注意力更专注', fontsize=12)\n",
        "plt.tight_layout()\n",
        "plt.savefig('../docs/assets/06_softmax_sharpness.png', dpi=100)\n",
        "plt.show()\n",
        "print('✓ Softmax 数值稳定性验证通过')\n",
    ]),

    # ── Cell 5: Toy Alignment Task ───────────────────────────────────────────
    cell("markdown", [
        "## 4. 玩具任务：序列复制中的注意力\n",
        "\n",
        "任务：输入序列 `[a, b, c, d, e]`，输出应该按顺序复制 `[a, b, c, d, e]`。\n",
        "理想情况下，生成第 $i$ 个输出时，注意力应集中在输入的第 $i$ 个位置（对角线注意力）。\n",
        "\n",
        "这里我们用**随机初始化**的注意力来演示基线（未经训练），\n",
        "然后手动设置'完美对齐'的参数来展示理想情况。\n"
    ]),
    cell("code", [
        "# 手工演示'完美对角注意力'\n",
        "T_demo = 6\n",
        "# 创建简单的输入 embedding（每个位置一个 one-hot 向量）\n",
        "encoder_states_demo = np.eye(T_demo)  # (T, T)：每行是一个位置的 embedding\n",
        "\n",
        "# 用不同的解码器隐状态（模拟对不同目标词的查询）\n",
        "# 理想：解码第 i 个词时，s_prev 和 encoder_states[i] 最相似\n",
        "alpha_matrix = np.zeros((T_demo, T_demo))\n",
        "\n",
        "attn_demo = BahdanauAttention(encoder_size=T_demo, decoder_size=T_demo, attn_size=T_demo)\n",
        "\n",
        "# 随机解码器状态 → 随机注意力\n",
        "for i in range(T_demo):\n",
        "    s = np.random.randn(T_demo)  # 随机解码器状态\n",
        "    _, alpha = attn_demo.forward(s, encoder_states_demo)\n",
        "    alpha_matrix[i] = alpha\n",
        "\n",
        "fig, axes = plt.subplots(1, 2, figsize=(10, 4))\n",
        "\n",
        "# 未训练的随机注意力\n",
        "axes[0].imshow(alpha_matrix, cmap='Blues', vmin=0, vmax=1)\n",
        "axes[0].set_title('随机初始化注意力（未训练）')\n",
        "axes[0].set_xlabel('编码器位置 j')\n",
        "axes[0].set_ylabel('解码器步骤 i')\n",
        "\n",
        "# 理想的对角注意力（用 eye 模拟训练后的结果）\n",
        "ideal_alpha = np.eye(T_demo)\n",
        "axes[1].imshow(ideal_alpha, cmap='Blues', vmin=0, vmax=1)\n",
        "axes[1].set_title('理想的对角注意力（训练后目标）')\n",
        "axes[1].set_xlabel('编码器位置 j')\n",
        "axes[1].set_ylabel('解码器步骤 i')\n",
        "\n",
        "plt.suptitle('注意力矩阵可视化', fontsize=12)\n",
        "plt.tight_layout()\n",
        "plt.savefig('../docs/assets/06_attention_heatmap.png', dpi=100)\n",
        "plt.show()\n",
        "print('注意力矩阵可视化完成')\n",
    ]),

    # ── Cell 6: One-hot attention special case ───────────────────────────────
    cell("markdown", [
        "## 5. 特殊情况验证\n",
        "\n",
        "**命题**：如果注意力权重 $\\alpha$ 是 one-hot 的（只有一个位置为 1，其余为 0），\n",
        "那么 context vector 就等于对应编码器位置的隐状态。\n",
    ]),
    cell("code", [
        "enc_states = np.random.randn(5, 8)\n",
        "\n",
        "# one-hot alpha: 第 2 个位置\n",
        "alpha_onehot = np.zeros(5)\n",
        "alpha_onehot[2] = 1.0\n",
        "\n",
        "context_manual = alpha_onehot @ enc_states\n",
        "expected = enc_states[2]\n",
        "\n",
        "print(f'one-hot alpha: {alpha_onehot}')\n",
        "print(f'context_manual: {context_manual.round(4)}')\n",
        "print(f'enc_states[2]:  {expected.round(4)}')\n",
        "assert np.allclose(context_manual, expected), 'one-hot 验证失败'\n",
        "print('✓ one-hot 注意力时 context = 对应编码器状态（数学正确）')\n",
        "\n",
        "# 均匀 alpha: context = 编码器隐状态的均值\n",
        "alpha_uniform = np.ones(5) / 5\n",
        "context_uniform = alpha_uniform @ enc_states\n",
        "expected_mean = enc_states.mean(axis=0)\n",
        "assert np.allclose(context_uniform, expected_mean), '均匀 alpha 验证失败'\n",
        "print('✓ 均匀注意力时 context = 编码器状态均值（数学正确）')\n",
    ]),

    # ── Cell 7: PyTorch Comparison ───────────────────────────────────────────
    cell("markdown", [
        "## 6. PyTorch 对比\n",
        "\n",
        "`torch.nn.MultiheadAttention` 实现的是**缩放点积注意力**（Scaled Dot-Product Attention），\n",
        "和 Bahdanau 加性注意力有所不同，但核心思路一致：分数 → softmax → 加权求和。\n",
    ]),
    cell("code", [
        "try:\n",
        "    import torch\n",
        "    import torch.nn as nn\n",
        "\n",
        "    # MultiheadAttention 期望 (seq_len, batch, embed_dim)\n",
        "    seq_len, batch, embed_dim = 5, 1, 8\n",
        "    mha = nn.MultiheadAttention(embed_dim=embed_dim, num_heads=1, batch_first=False)\n",
        "\n",
        "    query = torch.randn(1, batch, embed_dim)  # 单步 query\n",
        "    key = torch.randn(seq_len, batch, embed_dim)\n",
        "    value = key.clone()\n",
        "\n",
        "    with torch.no_grad():\n",
        "        output, attn_weights = mha(query, key, value)\n",
        "\n",
        "    print(f'PyTorch MHA output shape: {output.shape}')\n",
        "    print(f'PyTorch attn_weights shape: {attn_weights.shape}')\n",
        "    print(f'attn_weights sum: {attn_weights.sum().item():.4f}')\n",
        "    print('✓ PyTorch MultiheadAttention 验证通过')\n",
        "except ImportError:\n",
        "    print('PyTorch 未安装，跳过对比验证（纯 NumPy 实现已验证）')\n",
    ]),
]

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.9.0"},
    },
    "cells": cells,
}

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Written: {NB_PATH}")
